baseURL = "saint-ismier-immobilier.netlify.com"
disqusShortname = "themefisher-template"
googleAnalytics = ""
languageCode = "fr"
paginate = "6"
summaryLength = "10"
theme = "andromeda-light"
title = "Immobilier Saint-Ismier - Vente & Achat"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.85.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]
