author = "Themefisher"
buy_premium_popup = false
contact_form_action = "https://formspree.io/f/xyyoaewo"
copyright = "Claire Genot -  A votre service au 06 20 95 06 18"
custom_script = ""
description = "Immobilier Saint-Ismier - Votre agence immobilière en ligne sur Saint-Ismier. Pour tous vos projets immobiliers : estimation, vente et achat dans les communes de la Vallée du Grésivaudan. "
favicon = "images/favicon.png"
footer_info = ""
image = "images/logo-immoliaison.jpg"
logo = "images/logo-immoliaison.jpg"
logo_text = "Immobilier Saint Ismier"
logo_width = "240x"
mainSections = ["blog"]
reading_time = true
[contact_info]
address = "38330 Saint-Ismier, France"
email = ["claire.genot@immoliaison.fr"]
phone = ["+ 33 6 20 95 06 18"]
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[cta]
button = "Download The Theme"
button_link = "https://gethugothemes.com/products/andromeda/"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
enable = false
title = "Get Andromeda-Premium Now"
[imaging]
quality = 100
[navigation_button]
enable = true
label = "Biens en vente"
link = "https://saint-ismier-38.immoliaison.fr/"
[preloader]
enable = true
preloader = "images/favicon.png"
[[social]]
icon = "lab la-facebook-f"
link = "#!"
title = "Andromeda"
[[social]]
icon = "lab la-twitter"
link = "#!"
title = "AndromedaTweet"
[[social]]
icon = "lab la-linkedin-in"
link = "#!"
title = "AndromedaIn"
[[social]]
icon = "lab la-pinterest"
link = "#!"
title = "AndromedaPin"
