author = "Themefisher"
buy_premium_popup = false
contact_form_action = "https://formspree.io/f/xgernlzd"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "Immobilier Saint-Ismier"
favicon = "images/favicon.png"
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."
image = "images/logo-immoliaison.jpg"
logo = "images/logo.svg"
logo_text = "Andromeda"
logo_width = "240x"
mainSections = ["blog"]
reading_time = true
[contact_info]
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
email = ["info@andromeda.io", "smith@anderson.io", "john@anderson.io"]
phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[cta]
button = "Download The Theme"
button_link = "https://gethugothemes.com/products/andromeda/"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
enable = true
title = "Get Andromeda-Premium Now"
[imaging]
quality = 100
[navigation_button]
enable = true
label = "Buy Premium"
link = "https://gethugothemes.com/products/andromeda/"
[preloader]
enable = true
preloader = "images/favicon.png"
[[social]]
icon = "lab la-facebook-f"
link = "#!"
title = "Andromeda"
[[social]]
icon = "lab la-twitter"
link = "#!"
title = "AndromedaTweet"
[[social]]
icon = "lab la-linkedin-in"
link = "#!"
title = "AndromedaIn"
[[social]]
icon = "lab la-pinterest"
link = "#!"
title = "AndromedaPin"
